# fly.toml app configuration file generated for config-server-demo on 2025-10-09T19:25:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'config-server-demo'
primary_region = 'gru'

[env]
  OTEL_SERVICE_NAME = 'config-server'
  SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS = 'configs/'
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI = 'https://github.com/alefcarlos/flyio-demo'

[http_service]
  internal_port = 8888
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
