# fly.toml app configuration file generated for apiservice on 2025-10-09T01:22:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apiservice'
primary_region = 'gru'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  OTEL_SERVICE_NAME = 'apiservice'
  spring__cloud__config__uri = 'https://config-server-demo.fly.dev'